### ISSUE TITLE
Hardware v0.3 Testing - Tracking Issue

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/bms-c1#37]
This issue serves as a tracking issue for ongoing testing of the v0.3 hardware.

- [x] USB serial communication
- [x] UART serial communication
- [x] I2C communication (see https://github.com/LibreSolar/bms-firmware/issues/25)
- [x] CAN communication (see also https://github.com/zephyrproject-rtos/zephyr/pull/51100)
- [x] Pre-discharge circuit (see also https://github.com/LibreSolar/bms-c1/issues/36)
- [x] Turn on/off MOSFETs
- [ ] Balancing
- [x] BMS on/off button / connector
- [x] Voltage measurement
- [x] Current measurement
- [x] Temperature measurement
- [ ] Thermal performance
- [ ] Fuse circuit

**Comment by martinjaeger** [comment]
Pre-discharge circuit is working with latest firmware (https://github.com/LibreSolar/bms-firmware/commit/45df96b652b82a5a4ae333608ed071bd70f83ed5). Below tests were performed with a 24V LFP-Battery.

Yellow (CH1): PDSG (TP7), Blue (CH2): DSG (TP6)

1. BAT+ and BAT- terminals open.

![SCR295](https://user-images.githubusercontent.com/17674105/197529163-c1f0238a-b753-43fa-b1c2-b5f23ad4aefd.PNG)

2. BAT+ and BAT- terminals connected to 1200 uF electrolytic capacitor.

![SCR297](https://user-images.githubusercontent.com/17674105/197531416-c4c71778-77b6-4cf9-8bb3-8d78cd45834c.PNG)

The PDSG MOSFET is enabled first (P-channel MOSFET, i.e. gate pulled low) and pulls up the bus voltage through the resistor. The DSG follows the bus voltage. 250 ms after the bus voltage reached the battery voltage, the DSG FETs are enabled (gates 12V above battery voltage)

**Comment by martinjaeger** [comment]
The current and voltage measurement results from the bq76952 are less accurate than expected.

An example from testing:

- Pack current
  - BMS 3.76 A
  - Fluke multimeter: 3.95 A
- Pack voltage
  - BMS 26.98 V
  - Fluke multimeter: 27.20 V

The root cause has yet to be investigated. The bq76952 features different calibration features which can be leveraged to improve the accuracy.

**Comment by martinjaeger** [comment]
Which circuit problem do you have?

The LDO cannot handle the current required for the ESP32-C3.

**Comment by martinjaeger** [comment]
It really depends. Also a CAN transceiver can draw considerable amount of current. I didn't do the math, but dropping voltage from 60V to 3.3V will dissipate a lot of heat even for very small currents. For ESP32-C3 with WiFi it's not feasible for sure.

Let me know if you did some calculations and you think it may be doable with LDO only.

**Comment by martinjaeger** [comment]
Final test report was added to the repo, closing this issue.

https://github.com/LibreSolar/bms-c1/blob/main/testing/v0.3/README.md
